-- =============================================================
-- CycleX 初期データ
-- `supabase db reset` 実行時に自動適用される
-- =============================================================

-- -------------------------------------------------------------
-- ブランド一覧
--
-- 甲から支給された「ピストバイク」「ミニベロ　メーカー」の2資料をもとに、
-- 大文字小文字だけが違うもの(GIANT と Giant など)をまとめて一本化した。
-- 探しやすさを優先して、大文字小文字を無視したアルファベット順に並べる。
--
-- 追加するときは、すでに別の表記で入っていないかを確かめること。
-- name は一意制約だが大文字小文字は区別されるため、
-- 「GIANT」と「Giant」は別物として両方入ってしまう。
-- -------------------------------------------------------------

insert into public.brands (name) values
  ('A-bike'),
  ('A-Frame cycles'),
  ('AFFINITY CYCLES'),
  ('Alex Moulton'),
  ('ALL-CITY'),
  ('ALTAGE'),
  ('ANCHOR'),
  ('ANIMATO'),
  ('ARAYA'),
  ('ARGON 18'),
  ('ASAHI CYCLE'),
  ('BENELLI'),
  ('BESV'),
  ('Bianchi'),
  ('BIKE FRIDAY'),
  ('Bike R&D'),
  ('BIRDY'),
  ('BMC'),
  ('BOMBTRACK'),
  ('BRIDGESTONE'),
  ('Brompton'),
  ('BROOKLYN MACHINE WORKS'),
  ('BRUNO'),
  ('Campagnolo'),
  ('Cannondale'),
  ('Canyon'),
  ('CAPTAIN STAG'),
  ('CARACLE'),
  ('CarryMe'),
  ('CARTEL BIKES'),
  ('Cervélo'),
  ('Chalet Sports'),
  ('CHERUBIM'),
  ('CICLORE'),
  ('CINELLI'),
  ('CIPOLLINI'),
  ('Clean Speed'),
  ('Coleman'),
  ('Colnago'),
  ('CONTENDER'),
  ('Core-Japan'),
  ('CORRATEC'),
  ('CREATE BIKES'),
  ('CYCLE HEART'),
  ('DAHON'),
  ('Daytona'),
  ('DE ROSA'),
  ('Di Blasi'),
  ('Dolan'),
  ('DONTZER'),
  ('DOSNOVENTA'),
  ('DURCUS ONE'),
  ('Dynavector'),
  ('E.B.S'),
  ('EIGHTHINCH'),
  ('ENGINE11'),
  ('ESR'),
  ('evol'),
  ('FAIRWEATHER'),
  ('FELT'),
  ('FIAT'),
  ('FUJI'),
  ('FULCRUM'),
  ('GANWELL'),
  ('Giant'),
  ('GIC'),
  ('GIOS'),
  ('GREDDY'),
  ('GROWN'),
  ('GT'),
  ('HANWA'),
  ('HARRY QUINN'),
  ('HODAKA'),
  ('HOW I ROLL'),
  ('Hummingbird'),
  ('iruka'),
  ('JD BIKE'),
  ('KhodaaBloom'),
  ('KHS'),
  ('KIMORI'),
  ('KINFOLK'),
  ('KOGA'),
  ('KOLiBRI'),
  ('KORY YORK'),
  ('KUWAHARA'),
  ('LAND WALKER'),
  ('LE PINEAU'),
  ('LEADER'),
  ('Linus Bikes'),
  ('LOCAL BIKES'),
  ('LongEdge'),
  ('LOOK'),
  ('LOUIS GARNEAU'),
  ('MANHATTAN'),
  ('MARUISHI'),
  ('MASH'),
  ('MASI'),
  ('MATE.'),
  ('MAVERICK CYCLES'),
  ('MAVIC'),
  ('Merida'),
  ('MIYATA'),
  ('MOULTON'),
  ('NAGI BIKE'),
  ('NESTO'),
  ('NJS'),
  ('ORBEA'),
  ('Ori Bike'),
  ('OSSO'),
  ('OTOMO'),
  ('OUTRE'),
  ('OX ENGINEERING'),
  ('Pacific Cycles'),
  ('Panasonic'),
  ('PATTO BIKE'),
  ('PELAGO'),
  ('Pinarello'),
  ('PIZZ'),
  ('POLYGON'),
  ('populomobile'),
  ('Progressive'),
  ('PROVROS'),
  ('QUAD BIKES'),
  ('RAINBOW'),
  ('RALEIGH'),
  ('RENAULT'),
  ('Ribble'),
  ('Riese und Müller'),
  ('RITCHEY'),
  ('RITEWAY'),
  ('ROCKBIKES'),
  ('Root One'),
  ('ROSE'),
  ('SCHEIDEGG'),
  ('Scott'),
  ('Shimano'),
  ('sledBIKES'),
  ('SOMA FABRICATIONS'),
  ('Specialized'),
  ('SRAM'),
  ('STATE BICYCLE'),
  ('stjincycles'),
  ('STRiDA'),
  ('SUNSTAR'),
  ('SURLY'),
  ('Sven Cycles'),
  ('TANGE'),
  ('Tartaruga'),
  ('tern'),
  ('tokyobike'),
  ('Tommasini'),
  ('TRANS MOBILLY'),
  ('Trek'),
  ('TYRANT BIKES'),
  ('Tyrell'),
  ('UNIZE'),
  ('Unknown Bikes'),
  ('UNO PISTA'),
  ('VOTANI'),
  ('Weis MFG'),
  ('Weld One'),
  ('WILIER'),
  ('WINDCOG'),
  ('YAMAHA'),
  ('Zero Bike'),
  ('ZUNOW')
on conflict (name) do nothing;

-- -------------------------------------------------------------
-- 管理者アカウントの作成手順(手動)
--
-- 1. アプリから通常の会員登録を行う
-- 2. 以下を実行してロールを昇格する
--
--    update public.users set role = 'admin' where email = 'admin@example.com';
--
-- 管理画面上での管理者追加 UI は MVP の対象外(別紙1 第3項)。
-- -------------------------------------------------------------
